name: "nix-test"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: nixbuild/nix-quick-install-action@v22
      with:
        nix_conf: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v12
      with:
        name: zeek

    - name: Nix Flake Show
      run: nix flake show --all-systems

    - name: Check nix develop
      run: nix develop

    - name: Build wasm-bpf
      run: nix build .#wasm-bpf
